#!/bin/bash
echo "Result in base bestchol: $(awk "BEGIN{print strtonum(\"$WATER\", \"water\") + strtonum(\"$STIR\", \"stir\")}" | awk '{print toupper(strtonum($0, 10))}' | awk '{printf("%d\n", strtonum($0, "bestchol"))}')"
